### ISSUE TITLE
Unable to install this role using ansible-galaxy

### ISSUE THREAD

**Issue by Ben10k** [nicholasamorim/ansible-role-harbor#13]
When I try to install the role from Ansible Galaxy I get an error message:
```bash
$ sudo ansible-galaxy install nicholasamorim.harbor
- downloading role 'harbor', owned by nicholasamorim
- downloading role from https://github.com/nicholasamorim/ansible-role-harbor/archive/master.tar.gz
 [WARNING]: - nicholasamorim.harbor was NOT installed successfully: this role does not appear to have a meta/main.yml file.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

I believe that this is because ansible-galaxy expects a meta/main.**yml** but the meta file in this repository is meta/main.**yaml**

**Comment by nicholasamorim** [comment]
Hi, sorry for answering this so late, GH notifications....

I have just issued this command on my local machine and it worked fine:

```
$ ansible-galaxy install nicholasamorim.harbor
- downloading role 'harbor', owned by nicholasamorim
- downloading role from https://github.com/nicholasamorim/ansible-role-harbor/archive/master.tar.gz
- extracting nicholasamorim.harbor to /Users/nicholas/src/SocialMedia-2.0/automation/roles/nicholasamorim.harbor
- nicholasamorim.harbor (master) was installed successfully
```

I'm unsure of what's going on. What's your Ansible version, @ben10k? I'm using 2.7.10

**Comment by nicholasamorim** [comment]
Closing this as it works for me and issue has become stale.

**Comment by devopsz21** [comment]
Hi Nicholas, 

I tried to download your role with both src and galaxy way but it seems it is still an issue.Can you kindly check .
 
  - name: nicholasamorim.harbor
    src: https://github.com/nicholasamorim/ansible-role-harbor.git

 [WARNING]: - nicholasamorim.harbor was NOT installed successfully: this role does not appear to have a meta/main.yml file.

ansible-galaxy install -r requirements.yml --force 

Galaxy-way :   nicholasamorim.harbor
[WARNING]: - nicholasamorim.harbor was NOT installed successfully: this role
does not appear to have a meta/main.yml file.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

Really appreciate your role.

Thanks and Regards

**Comment by devopsz21** [comment]
Hi  Nicholas, 

After i upgraded the ansible version from ansible2.5 to 2.9.I was able to download seems to be an issue with ansible version. Not sure what could have caused. 

Thanks and Regards
